[package]
name = "rust-nation-uk-2024-async-workshop-1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_cpus = "1.16.0"
rand = "0.8.5"
rayon = "1.10.0"
