[package]
name = "rayon-processing-channels-of-chunks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.9.0"
thread_local = "1.1.8"
